-- MySQL Script generated by MySQL Workbench
-- Qua 30 Ago 2017 19:55:24 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mvc` DEFAULT CHARACTER SET utf8 ;
USE `db_mvc` ;